books/urls.py
from django.conf.urls import patterns, include, url

# URL-Config des book-Moduls
urlpatterns = patterns('books.views',
                       url('^add/$', 'add_buch'),
                       url(r'^(?P<id>\d+)/$', 'view_buch'),
                       url(r'^edit/(?P<id>\d+)/$', 'edit_buch'),
                       url(r'^del/(?P<id>\d+)/$', 'del_buch')
                       )

# statische HTML-Seite als Startseite ausliefern
urlpatterns += patterns('django.views.generic.simple',
                        (r'^$', 'direct_to_template', {'template': 'index.html'}),
)

codingcontest2012/urls.py
# -*- coding: utf-8 -*-
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

from tastypie.api import Api

from books.api.resources import AutorResource, BuchResource, GenreResource, SammlungResource, TagResource, VerlagResource

# Registrierung der einzelnen REST-Resourcen
v1_api = Api(api_name='v1')
v1_api.register(AutorResource())
v1_api.register(BuchResource())
v1_api.register(GenreResource())
v1_api.register(SammlungResource())
v1_api.register(TagResource())
v1_api.register(VerlagResource())

urlpatterns = patterns('',
    # Admin-Interface
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # URL der REST-Schnittstelle
    (r'^api/', include(v1_api.urls)),

    # Books-App einbinden
    url(r'^', include('books.urls')),

    # hochgeladene Dateien bereitstellen - nur für den
    # Entwicklungsprozess zu benutzen
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
)

urlpatterns += staticfiles_urlpatterns()

books/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Genre(models.Model):
    """
    Ein Genre umfasst eine bestimmte Kategorie eines Buches.

    Bspw. "Krimi", "Biografie" oä.
    Denkbar ein umfassenderes Genre-Modell als Taxonomie zu
    implementieren.
    """
    bezeichnung = models.CharField(max_length=200)

    def __unicode__(self):
        return self.bezeichnung

    class Meta:
        verbose_name = "Genre"
        verbose_name_plural = "Genres"


class Autor(models.Model):
    """
    Die Klasse Autor beschreibt genau eine Person, die als Autor auftritt.

    Weitere biografische Fakten denkbar und leicht
    erweiterbar.
    """
    vorname = models.CharField(max_length=200)
    nachname = models.CharField(max_length=200)

    def __unicode__(self):
        return self.vorname + " " + self.nachname

    class Meta:
        verbose_name = "Autor"
        verbose_name_plural = "Autoren"


class Verlag(models.Model):
    """
    Die als Verleger auftretende Firma.
    """
    bezeichnung = models.CharField(max_length=200)

    def __unicode__(self):
        return self.bezeichnung

    class Meta:
        verbose_name = "Verlag"
        verbose_name_plural = "Verlage"


class Tag(models.Model):
    """
    Ein Tag beschreibt eine weitere Klassifikations-Eigenschaft eines Buches.

    Im Gegensatz zum Genre bspw. beschreiben beliebig
    viele Tags ein bestimmtes Objekt näher.
    """
    bezeichnung = models.CharField(max_length=200)

    def __unicode__(self):
        return self.bezeichnung

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"


class Sammlung(models.Model):
    """
    Eine Sammlung umfasst mehrere Bücher und gruppiert diese so.

    Eine besondere Sammlung ist die ID 1, die "Wunschliste".
    """
    bezeichnung = models.CharField(max_length=200)

    def __unicode__(self):
        return self.bezeichnung

    class Meta:
        verbose_name = "Sammlung"
        verbose_name_plural = "Sammlungen"


class Buch(models.Model):
    """
    Diese Klasse, stellt die Hauptklasse des Systems dar.

    Ein Buch muss dabei zwingend lediglich einen Titel besitzen.
    Autor, Verlag etc. sind optional.
    """
    titel = models.CharField("Buchtitel", max_length=200)
    autor = models.ManyToManyField(Autor, blank=True, null=True)
    veroeffentlichung = models.DateField("Veröffentlichung", blank=True,
                                         null=True)
    verlag = models.ForeignKey(Verlag, blank=True, null=True)
    cover = models.ImageField("Buchcover", blank=True, null=True,
                              upload_to="images/cover/",
                              default="images/cover/blank.png")
    genre = models.ManyToManyField(Genre, blank=True, null=True)
    sammlung = models.ForeignKey(Sammlung, blank=True, null=True)
    # ISBN besitzt unter der Annahme von ISBN-13 mit Trennzeichen eine maximale
    # Länge von 17 Zeichen
    isbn = models.CharField("ISBN", max_length=17, blank=True)
    # Eine Bewertung auf einer posititiven Skala, je höher die Bewertung, desto
    # besser die Einschätzung des Benutzers
    bewertung = models.PositiveSmallIntegerField(blank=True, null=True)
    bemerkung = models.TextField(blank=True)
    tag = models.ManyToManyField(Tag, blank=True, null=True)
    preis = models.CharField(max_length=10, blank=True)
    # Zum sicheren Ablegen von Lesezeichen kann pro Buch eine Seitenzahl
    # als aktuelles Lesezeichen angelegt werden
    lesezeichen = models.PositiveIntegerField("Seitennr. des Lesezeichens",
                                              blank=True, null=True)

    def __unicode__(self):
        return self.titel

    class Meta:
        verbose_name = "Buch"
        verbose_name_plural = "Bücher"

books/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django.forms.fields import DateField, ChoiceField, IntegerField, CharField
from django.forms.widgets import RadioSelect, CheckboxSelectMultiple, Select, TextInput
from django.forms.extras.widgets import SelectDateWidget

from books.models import Buch


class BuchForm(ModelForm):
    """
    Formular für das Anlegen und Ändern von Buch-Instanzen.
    """
    titel = CharField(widget=TextInput(attrs={'size':'50'}))
    bewertung = ChoiceField(widget=Select, required=False, choices=(
            (1, "1"),
            (2, "2"),
            (3, "3"),
            (4, "4"),
            (5, "5")
            ))
    veroeffentlichung = DateField(widget=SelectDateWidget(), required=False)
    preis = CharField(widget=TextInput(attrs={'size':'10'}), required=False)
    lesezeichen = IntegerField(widget=TextInput(attrs={'size':'10'}), required=False)
    
    class Meta:
        model = Buch

books/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext

from books.forms import BuchForm
from books.models import Buch


def add_buch(request):
    """
    Funktion zum Hinzufügen eines Buches.

    Testet jeweils ob der Aufruf als POST oder GET
    abegesetzt wurde und liefert je nach dem das
    Ausgangsformular aus oder legt ein neues Buch an.
    """
    if request.method == 'POST':
        addForm = BuchForm(request.POST, request.FILES)
        if addForm.is_valid():
            addForm.save()
            return redirect("/")
    else:
        addForm = BuchForm()

    return render_to_response('addedit.html',
                              {'form': addForm, },
                              context_instance=RequestContext(request))


def edit_buch(request, id):
    """
    Funktion zum Bearbeiten einer Buch-Instanz.

    Verfährt beim Bearbeiten wie add_buch().
    """
    buch = get_object_or_404(Buch, pk=id)
    if request.method == 'POST':
        editForm = BuchForm(request.POST, request.FILES, instance=buch)
        if editForm.is_valid():
            editForm.save()
            return redirect("/")
    else:
        editForm = BuchForm(instance=buch)
    return render_to_response('addedit.html', {'id': id,
                                               'buch': buch,
                                               'form': editForm},
                              context_instance=RequestContext(request)) 


def del_buch(request, id):
    """
    Funktion zum Löschen einer Buch-Instanz.
    """
    Buch.objects.get(pk=id).delete()
    return redirect("/")


def view_buch(request, id):
    """
    Funktion zum Ausliefern aller Details einer Buch-Instanz.

    Es werden hierbei alle referenzierten Felder aufgelößt und
    an das Template weitergeleitet.
    """
    buch = get_object_or_404(Buch, pk=id)
    autoren = buch.autor.all()
    tags = buch.tag.all()
    genre = buch.genre.all()
    return render_to_response('details.html',
                              {'id': id,
                               'buch': buch,
                               'autoren': autoren,
                               'tags': tags,
                               'genre': genre},
                              context_instance=RequestContext(request))

books/templates/add.html
{% extends "base.html" %}

{% block head_extra %}
<script type="text/javascript">
  function isbn_schnellsuche(){
      var isbn = $("input[name=isbn]").val();
      $.ajax({
	  type: "GET",
	  url: "http://openlibrary.org/api/books",
	  data: {
	      'bibkeys': "ISBN:"+isbn,
	      'format': "jsonp"
	  },
	  dataType: "jsonp",
	  success: function(data){
	      console.log(data);
	  },
	  error: function(jqXHR, textStatus, errorThrown){
	      console.error(jqXHR, textStatus, errorThrown);
	  }
      });
  }
</script>
{% endblock %}

{% block content %}
<div class="col_2">
  <!-- Menu Vertical Left -->
  <ul class="menu vertical">
    <li class="current"><a href="/">&Uuml;bersicht</a></li>
    <li><a href="">Wunschliste</a></li>
    <li><a href="/stats/">Statistiken</a></li>
    <li><a href="/export/">Export</a></li>
  </ul>
</div>

<div class="col_10">
  <input type="text" name="isbn" value="" />
  <button class="medium" name="Schnellsuche" onclick="isbn_schnellsuche()">Schnellsuche</button>
  <form method="post" action="">
    {% csrf_token %}
    <table>
      {{form}}
    </table>
    <button type="submit" class="medium" name="Erstellen" value=""><span class="icon medium" data-icon="C"></span>Abschicken</button>
  </form>

</div>

{% endblock %}

books/templates/addedit.html
{% extends "base.html" %}

{% block head_extra %}
<script type="text/javascript">
  function success(data){
    console.log(data);
  }
  
  function isbn_schnellsuche(){
      var isbn = $("input[name=isbn]").val();
      $.ajax({
	  type: "GET",
	  url: "http://openlibrary.org/api/books",
	  data: {
	      'bibkeys': "ISBN:"+isbn,
	      'format': "jsonp",
              'callback': "success"
	  },
	  dataType: "jsonp",
	  success: function(data){
	      console.log("muh",data);
	  },
	  error: function(jqXHR, textStatus, errorThrown){
	      console.error(jqXHR, textStatus, errorThrown);
	  }
      });
  }

  $(document).ready(function(){
    $("#id_autor, #id_genre, #id_tag").addClass("fancy");
    $(".errorlist li").addClass("notice error");
  });
</script>
{% endblock %}

{% block content %}

<div class="col_10">
  <ul class="breadcrumbs alt1">
    <li><a href="/">Übersicht</a></li>
    {% if buch %}
      <li><a href="/{{buch.id}}/">{{buch.titel}}</a></li>
      <li><a href="">bearbeiten</a></li>
    {% else %}
      <li><a href="">neues Buch</a></li>
    {% endif %}
  </ul>
  
  <!-- <input id="text2" type="text" placeholder="ISBN-Nummer" class="col_3"/> -->
  <!-- <button class="medium" name="Schnellsuche" onclick="isbn_schnellsuche()">Schnellsuche</button> -->

  <!-- <hr class="alt2" /> -->

  <form enctype="multipart/form-data" method="post" action="">
    {% csrf_token %}
    <table id="addedit">
      {{form}}
    </table>
    <button type="submit" class="medium" name="Erstellen" value=""><span class="icon medium" data-icon="C"></span>Abschicken</button>
  </form>

</div>

{% endblock %}

books/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>CodingContest 2012</title>
    <meta charset="UTF-8">
    {% block jquery %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    {% endblock %}
    {% block head_extra %}{% endblock %}

    <!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <script type="text/javascript" src="{{ STATIC_URL }}js/prettify.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/kickstart.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/kickstart.css" media="all" />      
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css" media="all" />
  </head>
  <body>
    <a id="top-of-page"></a>
    <div id="wrap" class="clearfix">

      {% block content %}{% endblock %}

    </div><!-- END WRAP -->
  </body>
</html>

books/templates/details.html
{% extends "base.html" %}

{% block content %}

<div class="col_10">
  <ul class="breadcrumbs alt1">
    <li><a href="/">Übersicht</a></li>
    <li><a href="">{{buch.titel}}</a></li>
  </ul>

  <div class="col_3">
    <img src="{{MEDIA_URL}}{{buch.cover}}" class="cover" alt="Cover" />
  </div>

  <div class="col_8">
    <ul class="button-bar">
      <li><a href="/edit/{{buch.id}}/"><span class="icon" data-icon="7"></span> Bearbeiten</a></li>
      <li><a href="/del/{{buch.id}}/"><span class="icon" data-icon="T"></span> Löschen</a></li>
    </ul>

    <h2>{{buch.titel}}</h2>
    {% if autoren %}<span>von {{autoren|join:", "}}</span>{% endif %}
    <table class="infobox">
      <tr>
	<td>
	  <label>Veröffentlichung:</label>
	</td>
	<td>
	  <p>{{buch.veroeffentlichung|default:"nicht angegeben"}}</p>
	</td>
      </tr>
      <tr>
	<td>
	  <label>Verlag:</label>
	</td>
	<td>
	  <p>{{buch.verlag|default:"nicht angegeben"}}</p>
	</td>
      </tr>
      <tr>
	<td>
	  <label>Genre:</label>
	</td>
	<td>
	  <p>{{genre|join:", "|default:"nicht angegeben"}}</p>
	</td>
      </tr>
      <tr>
	<td>
	  <label>Sammlung:</label>
	</td>
	<td>
	  <p>{{buch.sammlung|default:"nicht angegeben"}}</p>
	</td>
      </tr>
      <tr>
	<td>
	  <label>ISBN:</label>
	</td>
	<td>
	  <p>{{buch.isbn|default:"nicht angegeben"}}</p>
	</td>
      </tr>
      <tr>
	<td>
	  <label>Bewertung:</label>
	</td>
	<td>
	  <p>{{buch.bewertung|default:"nicht angegeben"}}</p>
	</td>
      </tr>
      <tr>
	<td>
	  <label>Preis:</label>
	</td>
	<td>
	  <p>{{buch.preis|default:"nicht angegeben"}}</p>
	</td>
      </tr>
      <tr>
	<td>
	  <label>Lesezeichen:</label>
	</td>
	<td>
	  <p>{{buch.lesezeichen|default:"nicht angegeben"}}</p>
	</td>
      </tr>
      <tr>
	<td>
	  <label>Bemerkung:</label>
	</td>
	<td>
	  <p>{{buch.bemerkung|default:"nicht angegeben"}}</p>
	</td>
      </tr>
    </table>
    <div class="tags">
      {% for tag in tags %}
      <span class="icon small gray" data-icon="B"></span>&nbsp;{{tag}}
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

books/templates/index.html
{% extends "base.html" %}

{% block jquery %}{% endblock %}
{% block head_extra %}

<link href="/api/v1/buch/?format=jsonp&username=admin&api_key=00405cc4d92866272602ef2f476f97b6e4f266f9" type="application/jsonp" rel="exhibit/data" ex:converter="converter"/>
<script src="http://api.simile-widgets.org/exhibit/2.2.0/exhibit-api.js" type="text/javascript"></script>
<script src="http://static.simile.mit.edu/exhibit/extensions-2.0/time/time-extension.js"></script>
<script type="text/javascript">
// Exhibit modifiziert den Seitentitel standardmäßig unschön, durch
// Überschreiben der Funktion wird dies verhindert.
SimileAjax.History.formatHistoryEntryTitle = function(actionLabel) {
    return SimileAjax.History._plainDocumentTitle;
}
  
/**
 * Diese Funktion wandelt das von der REST-Schnittstelle
 * erhaltene JSON in das für Exhibit benötigte spezifische
 * JSON-Format um.
 **/
function converter(json){
    json.items = json.objects;
    delete json.objects;
    for (item in json.items){
        item = json.items[item];
	item.label = item.titel;
	delete item.titel;
        item.myid = item.id;
        if (sam = item.sammlung)
            item.sammlung = sam.bezeichnung;
        if (verlag = item.verlag)
            item.verlag = verlag.bezeichnung;
        if (autoren = item.autor){
            for (autor in autoren){
		autoren[autor] = autoren[autor].vorname+" " + autoren[autor].nachname;
            }
        }
	if (genres = item.genre){
            for (genre in genres){
		genres[genre] = genres[genre].bezeichnung;
            }
        }
	if (tags = item.tag){
            for (tag in tags){
		tags[tag] = tags[tag].bezeichnung;
            }
        }
    }
    json.properties = {
	'label': {
	    label: "Titel"
	},
	'autor': {
	    label: "Autor"
	},
	'veroeffentlichung': {
	    label: "Veröffentlichung",
	    valueType: "date"
	},
        'genre': {
            label: "Genre"
        },
	'verlag': {
	    label: "Verlag"
	},
	'isbn': {
	    label: "ISBN",
	},
	'bemerkung': {
	    label: "Bemerkung"
	},
	'preis': {
	    label: "Preis",
            valueType: "number"
	},
	'lesezeichen': {
	    label: "Lesezeichen"
	},
	'bewertung': {
	    valueType: "number",
	    label: "Bewertung"
	}
    };
    return json;
}
</script>

{% endblock %}
    
{% block content %}

<div class="col_9">
  <a class="button orange" href="/add/">
    <span class="icon medium" data-icon="+"></span>neues Buch
  </a>

  <div ex:role="viewPanel">
    <!-- Vorschaubilder -->
    <div ex:role="view" ex:viewClass="Thumbnail" ex:showHeader="false" ex:paginate="true" style="padding: 1em 0.5in;">
      <div ex:role="lens" style="padding:10px;text-align:center">
      	<a ex:href-content="concat('/', .myid)">
      	  <img ex:src-content=".cover" class="cover" /><br/>
      	  <span ex:content=".label"></span>
      	</a>
      </div>
    </div>

    <!-- Tabellenansicht -->
    <div ex:role="view" ex:viewClass="Tabular"
	 ex:columns=".label, .autor, .genre, .bewertung" >
      <table>
        <tr>
          <td><a ex:href-content="concat('/', .myid)"><span ex:content=".label"></span></a></td>
          <td><span ex:content=".autor"></span></td>
	  <td><span ex:content=".genre"></span></td>
	  <td><span ex:content=".bewertung"></span></td>
        </tr>
      </table>
    </div>

    <!-- Timeline-Ansicht -->
    <div ex:role="view" 
	 ex:viewClass="Timeline"
	 ex:showHeader="false"
	 ex:showSummary="false"
	 ex:start=".veroeffentlichung"
	 ex:end=".veroeffentlichung">
    </div>
  </div>
</div>

<div class="col_3">
  <!-- Such- und Filterabschnitt -->
   <div ex:role="facet" 
	ex:facetClass="TextSearch"
	ex:facetLabel="Suche">
   </div><br/>

   <div ex:role="facet" 
	ex:facetClass="Cloud"
	ex:expression=".autor"
	ex:facetLabel="Autoren" >
   </div><br/>

   <div ex:role="facet" 
	ex:facetClass="Cloud"
	ex:expression=".genre"
	ex:facetLabel="Genre" >
   </div><br/>
   
   <div ex:role="facet" 
	ex:expression=".sammlung"
	ex:facetLabel="Sammlungen" >
   </div><br/>

   <div ex:role="facet" 
	ex:expression=".verlag"
	ex:facetLabel="Verlage" >
   </div><br/>

   <div ex:role="facet" 
	ex:facetClass="Cloud"
	ex:expression=".tag"
	ex:facetLabel="Tags" >
   </div><br/>

</div>
{% endblock %}